# Generated by Django 4.0.5 on 2022-07-26 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_todo_process_todo_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo_process',
            name='user',
        ),
        migrations.DeleteModel(
            name='ToDo_completed',
        ),
        migrations.DeleteModel(
            name='ToDo_process',
        ),
    ]
