# Generated by Django 4.0.5 on 2022-07-26 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_todo_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='status',
        ),
    ]
