# Generated by Django 4.0.5 on 2022-07-26 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_todo_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='status',
            field=models.TextField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
